resources:
  entity:node:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
        - cookie
    POST:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    PATCH:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  entity:taxonomy_vocabulary:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
        - cookie
    POST:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    PATCH:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  entity:taxonomy_vocabulary:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
        - cookie
    POST:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    PATCH:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
