content_direct.remote_site.*:
  type: config_entity
  label: 'Remote Site config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    protocol:
      type: string
      label: 'Protocol'
    host:
      type: string
      label: 'Remote Host'
    port:
      type: string
      label: 'Port'
    format:
      type: string
      label: 'Format'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
