content_direct.settings:
  type: config_object
  label: 'Content Direct Settings'
  mapping:
    protocol:
      type: string
      label: 'Protocol'
    host:
      type: string
      label: 'Remote Host'
    port:
      type: string
      label: 'Port'
    format:
      type: string
      label: 'Format'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
#    token:
#      type: string
#      label: 'CSRF Token'
